### ISSUE TITLE
error: redefinition of typedef ‘p_s8query’

### ISSUE THREAD

**Issue by jeffdaily** [RonnySoak/libssa#5]
gcc -Wall -O3 -std=c99  -march=native -c -o src/algo/8/search_8.o src/algo/8/search_8.c
In file included from src/algo/8/search_8.c:21:
src/algo/8/search_8_util.h:44: error: redefinition of typedef ‘p_s8query’
src/algo/8/search_8.h:31: note: previous declaration of ‘p_s8query’ was here
make: *** [src/algo/8/search_8.o] Error 1

**Comment by RonnySoak** [comment]
I removed the redefinition
